apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: WebService1
  description: TDG test web service registration
  annotations:
    github.com/project-slug: GHSlug
  tags: 
    - atlas-go
    - rest-api
  links:
    - url: https://github.com/tim-geissler-sp/test-catalog
      title: Github Repo
      icon: github
      type: admin-dashboard
spec:
  type: service
  lifecycle: experimental
  owner: tdg
  system: Saas